# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability
# !!! Modify with care !!!

mission_start:
  # default_outcome: Completed
  path_topic_name: /mabi_highlevel_controller/path_direct
  timeout: 10.0

nav_to_wall:
  default_outcome: Completed
  distance_from_wall: 3.0
  normal_direction: -1                                            # can be either 1 or -1
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  roco_controller: MpcPathFollowingController
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  timeout: 30.0                                                   # max time to reach the goal within accuracy
  tolerance_m: 0.3                                                # position accuracy (meters)
  tolerance_deg: 10                                               # position accuracy (degrees)

hal_positioning:
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  sub_roco_controller: MabiExternalPathEndeffectorTrackingController  # desired roco controller
  sub_controller_manager_namespace: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path
  target_offset:                                                  # target pose of the end-effector in the marker frame, with format t: [x, y, z], q: [qx, qy, qz, qw].
    t: [-4.0, 1.0, 1.0]                                            # TODO: Change these with sensible values!
    q: [ -0.7071068, 0, 0.7071068, 0 ]                  # -90 y, 180 z

  reference_frame_id: marker
  end_effector_frame_id: ENDEFFECTOR

arm_recorded_motion:
  #default_outcome: NoMorePoses
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  sub_roco_controller: MabiExternalPathAdmittanceEndeffectorTrackingController  # desired roco controller
  sub_controller_manager_namespace: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: ENDEFFECTOR
  poses:                                                          # list of target poses in format t: [x, y, z], q: [qx, qy, qz, qw]. Note: these poses are relative to the previous pose of the end effector.
    - t: [0.0, 0.0, 0.0]
      q: [ 0.0434534, 0.0870728, 0.0038017, 0.9952465 ]
    - t: [0.0, 0.0, 0.0]
      q: [ 0.0434534, 0.0870728, 0.0038017, 0.9952465 ]
    - t: [0.0, 0.0, 0.0]
      q: [ 0.0429567, -0.1734829, -0.0075744, 0.9838704 ]

hal_data_collection:
  default_outcome: Completed
  service_name: /hal_take_measurement
  timeout: 10.0

hal_optimization:
  default_outcome: Completed
  hal_optimization_service_name: /high_accuracy_localize
  hal_timeout: 10.0                                               # max time to wait for the service to be advertised

init_grinding:
  default_outcome: Completed
  timeout: 10.0

grinding_positioning:
  default_outcome: Completed
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: end_effector

  offset:                                                         # this is the offset expressed in the grinding path frame : T_grind_ee
    t: [-0.2, 0.0, 0.0]
    q: [0.0, 0.0, 0.0, 1.0]

move_into_contact:
  default_outcome: Completed
  timeout: 30.0                                                   # max time before considering the pose reached
  wrench_service_name: /setDesiredWrenchCurrentEEFrame
  reset_reference: true
  force:
    x: 0.0
    y: 0.0
    z: -50.0
  ft_imu_sensor_topic: "/gravity_compensated_wrench"
  travel:                                                         # this is the travel for making contact in the end effector frame
    t: [0.0, 0.0, 0.2]
    q: [0.0, 0.0, 0.0, 1.0]
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  sub_roco_controller: MabiExternalPathAdmittanceEndeffectorTrackingController  # desired roco controller
  sub_controller_manager_namespace: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path
  reference_frame_id: ENDEFFECTOR
  end_effector_frame_id: ENDEFFECTOR



follow_grinding_path:
  # default_outcome: Completed
  timeout: 10.0
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  sub_roco_controller: MabiExternalPathEndeffectorTrackingController #MabiExternalPathAdmittanceEndeffectorTrackingController  # desired roco controller
  sub_controller_manager_namespace: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: world
  end_effector_frame_id: ENDEFFECTOR

  wall_penetration: 0.02

as_built_sensing:
  default_outcome: Completed
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: end_effector

  scanning_pose:
    t: [0.0, 0.0, 0.0]
    q: [0.0, 0.0, 0.0, 1.0]
