# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability
# !!! Modify with care !!!

mission_start:
  default_outcome: Completed
  path_topic_name: /mabi_highlevel_controller/path_direct
  timeout: 10.0

nav_to_wall:
  default_outcome: Completed
  distance_from_wall: 3.0
  normal_direction: -1                                            # can be either 1 or -1
  goal_pose_topic: /move_base_simple/goal
  base_pose_topic: /base_pose_measured
  roco_controller: MpcTrackLocalPlan
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  timeout: 30.0                                                   # max time to reach the goal within accuracy
  tolerance_m: 0.3                                                # position accuracy (meters)
  tolerance_deg: 10                                               # position accuracy (degrees)

arm_recorded_motion:
  #default_outcome: PoseReached, NoMorePoses, Aborted
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: end_effector
  poses:                                                          # list of target poses in format t: [x, y, z], q: [qx, qy, qz, qw]
    - t: [0.0, 0.0, 0.0]
      q: [0.0, 0.0, 0.0, 1.0]
    - t: [0.2, 1.0, 3.0]
      q: [0.0, 0.0, 0.707, 0.707]

hal_data_collection:
  #default_outcome: Completed, Aborted
  service_name: /hal_take_measurement
  timeout: 10.0

hal_optimization:
  #default_outcome: Completed, Aborted
  hal_optimization_service_name: /high_accuracy_localize
  confusor_update_service_name: /to_define
  hal_timeout: 10.0                                               # max time to wait for the service to be advertised
  confusor_timeout: 10.0                                          # max time to wait for the service to be advertised
  hal_update_timeout: 10.0                                        # max time to wait for the hal update message (sent then to confusor)

init_grinding:
  default_outcome: Completed
  timeout: 10.0

grinding_positioning:
  default_outcome: Completed
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: end_effector

  offset:                                                         # this is the offset expressed in the grinding path frame : T_grind_ee
    t: [-0.2, 0.0, 0.0]
    q: [0.0, 0.0, 0.0, 1.0]

move_into_contact:
  default_outcome: Completed
  wrench_service_name: /setDesiredWrenchCurrentEEFrame
  reset_reference: true
  force:
    x: 0.0
    y: 0.0
    z: -50.0


follow_grinding_path:
  default_outcome: Completed
  timeout: 10.0
  roco_controller: MabiMobileCombinedController                     # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: end_effector

as_built_sensing:
  default_outcome: Completed
  timeout: 10.0                                                   # max time before considering the pose reached
  roco_controller: MabiMobileCombinedController                   # desired roco controller
  controller_manager_namespace: /mabi_mobile_highlevel_controller
  path_topic_name: /mabi_mobile_highlevel_controller/MabiMobileCombinedController/external_path

  reference_frame_id: base
  end_effector_frame_id: end_effector

  scanning_pose:
    t: [0.0, 0.0, 0.0]
    q: [0.0, 0.0, 0.0, 1.0]