# Config file for the combined mission
# Namespaces mirror (optionally) the state for better readability

home_robot:
  some_other_key: "value"

reach_detection_hotspot:
  some_other_key: "value"

detect:
  detection_service_name : "/detection_service"

new_viewpoint:
  joints_configurations:
    - [0.0 0.0 0.0 0.0 0.0 0.0 0.0]
    - [0.0 0.0 0.0 0.0 0.0 0.0 0.0]
    - [0.0 0.0 0.0 0.0 0.0 0.0 0.0]
